Repository grapheneX/grapheneX, pull requests merged in 2019-08, with the labels that each got.

#87 Revert commit ac1ef52 - remove modules
  graphenex/modules.json
Labels: fix

#88 Fix & add removed modules
  graphenex/modules.json
Labels: fix

#90 Merge branch 'dev' into master (v1.1.2)
  .bumbversion.cfg
  graphenex/__init__.py
  graphenex/modules.json
  setup.py
Labels: release

#91 Remove import_colorama function & fix import
  graphenex/core/utils/helpers.py
Labels: fix

#92 Merge branch 'dev' into master (v1.1.3)
  .bumbversion.cfg
  graphenex/__init__.py
  graphenex/core/utils/helpers.py
  setup.py
Labels: release

#93 Added system monitor
  Pipfile
  Pipfile.lock
  graphenex/core/utils/helpers.py
  graphenex/core/web/__init__.py
  graphenex/core/web/providers.py
  graphenex/core/web/static/css/index.css
  graphenex/core/web/static/js/index.js
  graphenex/core/web/static/js/providers.js
  graphenex/core/web/templates/index.html
  graphenex/core/web/views.py
  setup.py
Labels: enchancement, feature

#94 Refactor system monitor feature
  graphenex/core/utils/helpers.py
  graphenex/core/utils/sysinfo.py
  graphenex/core/web/__init__.py
  graphenex/core/web/providers.py
  graphenex/core/web/templates/index.html
  graphenex/core/web/views.py
Labels: enchancement, refactor

#96 Changed human friendly output in web interface network monitor
  Pipfile.lock
  graphenex/core/utils/sysinfo.py
  graphenex/core/web/__init__.py
  graphenex/core/web/views.py
Labels: enchancement, feature, fix
