Repository grapheneX/grapheneX, pull requests merged in 2019-05, with the labels that each got.

#32 Project Refactor II
  core/cli/commands.py
  core/cli/shell.py
  core/linux/exec.py
  core/utils/helpers.py
  core/utils/logcl.py
  core/win/editreg.py
  grapheneX.py
Labels: refactor

#33 Web Interface Initialization
  core/web/server.py
  core/web/templates/index.html
  requirements.txt
Labels: feature

#34 Web Page & Libraries
  core/web/server.py
  core/web/static/css/bootstrap.min.css
  core/web/static/css/index.css
  core/web/static/js/bootstrap.min.js
  core/web/static/js/index.js
  core/web/static/js/jquery-3.2.1.js
  core/web/static/js/socket.io.min.js
  core/web/templates/index.html
Labels: arrangement

#36 Web Interface Main Page
  core/web/static/css/aos.css
  core/web/static/css/fa_all.css
  core/web/static/css/index.css
  core/web/static/images/graphenex_logo_white.png
  core/web/static/js/aos.js
  core/web/static/js/index.js
  core/web/static/js/popper.min.js
  core/web/static/webfonts/fa-brands-400.eot
  core/web/static/webfonts/fa-brands-400.svg
  core/web/static/webfonts/fa-brands-400.ttf
  core/web/static/webfonts/fa-brands-400.woff
  core/web/static/webfonts/fa-brands-400.woff2
  core/web/static/webfonts/fa-regular-400.eot
  core/web/static/webfonts/fa-regular-400.svg
  core/web/static/webfonts/fa-regular-400.ttf
  core/web/static/webfonts/fa-regular-400.woff
  core/web/static/webfonts/fa-regular-400.woff2
  core/web/static/webfonts/fa-solid-900.eot
  core/web/static/webfonts/fa-solid-900.svg
  core/web/static/webfonts/fa-solid-900.ttf
  core/web/static/webfonts/fa-solid-900.woff
  core/web/static/webfonts/fa-solid-900.woff2
  core/web/templates/index.html
Labels: feature

#35 Web Interface & Argparser
  core/utils/argparser.py
  core/utils/helpers.py
  grapheneX.py
Labels: feature

#37 Socket IO Connection
  core/web/server.py
  core/web/static/js/index.js
Labels: feature

#38 Changed project struct and added system information
  Pipfile
  Pipfile.lock
  core/utils/helpers.py
  core/web/__init__.py
  core/web/server.py
  core/web/static/js/index.js
  core/web/templates/index.html
  core/web/views.py
  grapheneX.py
Labels: enchancement

#39 Web Interface Refactor I
  core/cli/commands.py
  core/cli/shell.py
  core/utils/helpers.py
  core/web/__init__.py
  core/web/static/js/index.js
  core/web/templates/index.html
  core/web/views.py
  grapheneX.py
Labels: enchancement, refactor

#40 Web Interface Module List
  core/web/static/js/index.js
  core/web/templates/index.html
  core/web/views.py
Labels: feature

#42 Web Interface Module Info
  core/web/templates/index.html
  core/web/views.py
Labels: feature

#44 namespaces, modules, rendering and other wonderful things
  core/hrd/win/firewall.py
  core/web/__init__.py
  core/web/static/css/index.css
  core/web/static/js/index.js
  core/web/templates/index.html
  core/web/views.py
Labels: enchancement, feature

#45 Web Refactor I & Harden Command
  core/cli/commands.py
  core/web/__init__.py
  core/web/static/css/index.css
  core/web/static/js/index.js
  core/web/templates/index.html
  core/web/views.py
Labels: enchancement, feature, refactor

#47 Web Interface Framework Design
  core/web/__init__.py
  core/web/static/css/index.css
  core/web/static/js/index.js
  core/web/templates/index.html
Labels: arrangement, feature

#48 Interactive Shell <add()>
  core/cli/commands.py
  core/cli/help.py
Labels: feature

#49 Checking Module Integrity
  core/utils/helpers.py
Labels: feature

#50 changed module strategy
  core/cli/commands.py
  core/hrd/__init__.py
  core/hrd/linux/kernel.py
  core/hrd/win/firewall.py
  core/utils/helpers.py
  core/web/views.py
  modules.json
Labels: arrangement, enchancement, feature
