Repository grapheneX/grapheneX, pull requests merged in 2019-06, with the labels that each got.

#51 Framework Features for CLI & Improvements
  Pipfile
  Pipfile.lock
  core/cli/commands.py
  core/cli/help.py
  core/hrd/__init__.py
  core/hrd/exec.py
  core/linux/exec.py
  core/utils/argparser.py
  core/utils/helpers.py
  core/web/__init__.py
  core/web/static/js/index.js
  core/web/templates/index.html
  core/web/views.py
  core/win/editreg.py
  core/win/exec.py
  requirements.txt
Labels: enchancement, feature, refactor

#52 Added namespace selection in Web
  core/web/__init__.py
  core/web/static/css/index.css
  core/web/static/js/index.js
  core/web/static/js/listgroup.min.js
  core/web/templates/index.html
Labels: feature

#54 Adding Modules From Web Interface
  core/web/static/css/index.css
  core/web/static/js/index.js
  core/web/templates/index.html
  core/web/views.py
Labels: enchancement, feature

#53 Fixed some potential problems
  core/cli/commands.py
  core/utils/helpers.py
Labels: fix

#56 Use list instead of rawlist on manage command
  README.md
  core/cli/commands.py
  core/utils/helpers.py
Labels: fix

#57 Fixed list command bug
  core/cli/commands.py
  core/utils/argparser.py
  core/web/__init__.py
  core/web/static/js/template.js
  grapheneX.py
  modules.json
Labels: arrangement, fix

#58 Fix different directory bug & refactor argparse
  core/cli/commands.py
  core/utils/argparser.py
  core/utils/helpers.py
  grapheneX.py
Labels: arrangement, fix, refactor
