Repository grapheneX/grapheneX, pull requests merged in 2019-07, with the labels that each got.

#59 New Linux Modules
  modules.json
Labels: feature

#60 Documentation & Preset Feature
  CONTRIBUTING.md
  Pipfile.lock
  README.md
  core/cli/commands.py
  core/cli/help.py
  core/hrd/__init__.py
  core/utils/helpers.py
  core/web/__init__.py
  grapheneX.py
  modules.json
  requirements.txt
Labels: arrangement, enchancement, feature, refactor

#61 PYPI installation and final touches
  .bumbversion.cfg
  .gitattributes
  MANIFEST.in
  Pipfile
  Pipfile.lock
  README.md
  graphenex/__init__.py
  graphenex/__main__.py
  graphenex/core/cli/commands.py
  graphenex/core/cli/help.py
  graphenex/core/cli/shell.py
  graphenex/core/hrd/__init__.py
  graphenex/core/hrd/exec.py
  graphenex/core/utils/helpers.py
  graphenex/core/utils/logcl.py
  graphenex/core/web/__init__.py
  graphenex/core/web/static/css/aos.css
  graphenex/core/web/static/css/bootstrap.min.css
  graphenex/core/web/static/css/fa_all.css
  graphenex/core/web/static/css/index.css
  graphenex/core/web/static/images/graphenex_logo_white.png
  graphenex/core/web/static/js/aos.js
  graphenex/core/web/static/js/bootstrap.min.js
  graphenex/core/web/static/js/index.js
  graphenex/core/web/static/js/jquery-3.2.1.js
  graphenex/core/web/static/js/listgroup.min.js
  graphenex/core/web/static/js/popper.min.js
  graphenex/core/web/static/js/socket.io.min.js
  graphenex/core/web/static/js/template.js
  graphenex/core/web/static/webfonts/fa-brands-400.eot
  graphenex/core/web/static/webfonts/fa-brands-400.svg
  graphenex/core/web/static/webfonts/fa-brands-400.ttf
  graphenex/core/web/static/webfonts/fa-brands-400.woff
  graphenex/core/web/static/webfonts/fa-brands-400.woff2
  graphenex/core/web/static/webfonts/fa-regular-400.eot
  graphenex/core/web/static/webfonts/fa-regular-400.svg
  graphenex/core/web/static/webfonts/fa-regular-400.ttf
  graphenex/core/web/static/webfonts/fa-regular-400.woff
  graphenex/core/web/static/webfonts/fa-regular-400.woff2
  graphenex/core/web/static/webfonts/fa-solid-900.eot
  graphenex/core/web/static/webfonts/fa-solid-900.svg
  graphenex/core/web/static/webfonts/fa-solid-900.ttf
  graphenex/core/web/static/webfonts/fa-solid-900.woff
  graphenex/core/web/static/webfonts/fa-solid-900.woff2
  graphenex/core/web/templates/index.html
  graphenex/core/web/views.py
  graphenex/modules.json
  requirements.txt
  setup.py
Labels: arrangement, feature

#62 Project Refactor III
  .gitignore
  graphenex/__main__.py
  graphenex/core/cli/commands.py
  graphenex/core/hrd/__init__.py
  graphenex/core/utils/helpers.py
  graphenex/modules.json
  setup.py
Labels: enchancement, refactor

#63 Added new linux modules
  graphenex/core/utils/helpers.py
  graphenex/modules.json
Labels: arrangement

#64 Project Refactor IV
  README.md
  graphenex/__main__.py
  graphenex/core/cli/commands.py
  graphenex/core/cli/help.py
  graphenex/core/cli/shell.py
  graphenex/core/hrd/__init__.py
  graphenex/core/hrd/exec.py
  graphenex/core/utils/helpers.py
  graphenex/core/utils/logcl.py
  graphenex/core/web/__init__.py
  graphenex/core/web/static/css/index.css
  graphenex/core/web/static/js/index.js
  graphenex/core/web/static/js/template.js
  graphenex/core/web/templates/index.html
  graphenex/core/web/views.py
  graphenex/modules.json
Labels: enchancement, refactor

#65 Merge branch 'dev' into master (v1.0.1)
  .bumbversion.cfg
  .gitattributes
  .gitignore
  CONTRIBUTING.md
  MANIFEST.in
  Pipfile
  Pipfile.lock
  README.md
  graphenex/__init__.py
  graphenex/__main__.py
  graphenex/core/cli/commands.py
  graphenex/core/cli/help.py
  graphenex/core/cli/shell.py
  graphenex/core/hrd/__init__.py
  graphenex/core/hrd/exec.py
  graphenex/core/utils/helpers.py
  graphenex/core/utils/logcl.py
  graphenex/core/web/__init__.py
  graphenex/core/web/static/css/aos.css
  graphenex/core/web/static/css/bootstrap.min.css
  graphenex/core/web/static/css/fa_all.css
  graphenex/core/web/static/css/index.css
  graphenex/core/web/static/images/graphenex_logo_white.png
  graphenex/core/web/static/js/aos.js
  graphenex/core/web/static/js/bootstrap.min.js
  graphenex/core/web/static/js/index.js
  graphenex/core/web/static/js/jquery-3.2.1.js
  graphenex/core/web/static/js/listgroup.min.js
  graphenex/core/web/static/js/popper.min.js
  graphenex/core/web/static/js/socket.io.min.js
  graphenex/core/web/static/js/template.js
  graphenex/core/web/static/webfonts/fa-brands-400.eot
  graphenex/core/web/static/webfonts/fa-brands-400.svg
  graphenex/core/web/static/webfonts/fa-brands-400.ttf
  graphenex/core/web/static/webfonts/fa-brands-400.woff
  graphenex/core/web/static/webfonts/fa-brands-400.woff2
  graphenex/core/web/static/webfonts/fa-regular-400.eot
  graphenex/core/web/static/webfonts/fa-regular-400.svg
  graphenex/core/web/static/webfonts/fa-regular-400.ttf
  graphenex/core/web/static/webfonts/fa-regular-400.woff
  graphenex/core/web/static/webfonts/fa-regular-400.woff2
  graphenex/core/web/static/webfonts/fa-solid-900.eot
  graphenex/core/web/static/webfonts/fa-solid-900.svg
  graphenex/core/web/static/webfonts/fa-solid-900.ttf
  graphenex/core/web/static/webfonts/fa-solid-900.woff
  graphenex/core/web/static/webfonts/fa-solid-900.woff2
  graphenex/core/web/templates/index.html
  graphenex/core/web/views.py
  graphenex/modules.json
  setup.py
Labels: release

#73 Secure the web server
  .all-contributorsrc
  .gitattributes
  Pipfile.lock
  README.md
  graphenex/core/web/__init__.py
  graphenex/core/web/static/css/index.css
  graphenex/core/web/templates/control.html
  graphenex/core/web/views.py
Labels: enchancement, feature

#74 Web Interface Improvements
  README.md
  graphenex/core/cli/commands.py
  graphenex/core/utils/helpers.py
  graphenex/core/web/__init__.py
  graphenex/core/web/static/images/favicon.ico
  graphenex/core/web/templates/404.html
  graphenex/core/web/templates/auth.html
  graphenex/core/web/templates/index.html
  graphenex/core/web/views.py
Labels: enchancement, feature

#75 Merge branch 'dev' into master (v1.1.0)
  .bumbversion.cfg
  Pipfile.lock
  README.md
  graphenex/__init__.py
  graphenex/core/cli/commands.py
  graphenex/core/utils/helpers.py
  graphenex/core/web/__init__.py
  graphenex/core/web/static/css/index.css
  graphenex/core/web/static/images/favicon.ico
  graphenex/core/web/templates/404.html
  graphenex/core/web/templates/auth.html
  graphenex/core/web/templates/index.html
  graphenex/core/web/views.py
  setup.py
Labels: release

#79 Dockerize
  Docker/Dockerfile
  README.md
Labels: enchancement

#78 Update project dependencies
  Pipfile
  Pipfile.lock
  README.md
  graphenex/core/utils/helpers.py
  graphenex/modules.json
  setup.py
Labels: arrangement, fix

#83 Merge branch 'dev' into master (v1.1.1)
  .bumbversion.cfg
  Pipfile
  Pipfile.lock
  README.md
  docker/Dockerfile
  graphenex/__init__.py
  graphenex/core/utils/helpers.py
  graphenex/modules.json
  setup.py
Labels: release

#80 Update README.md
  README.md
Labels: enchancement

#86 Add Docker build badge to README
  README.md
Labels: enchancement
