Repository grapheneX/grapheneX, pull requests merged in 2019-04, with the labels that each got.

#6 print_header & logging improvements
  core/helpers.py
  core/logcl.py
  grapheneX.py
  requirements.txt
Labels: enchancement, refactor

#9 exec.py improved
  core/linux/exec.py
Labels: enchancement

#7 Created win/exec.py
  core/win/exec.py
Labels: feature, needs research

#8 argparser.py added
  core/argparser.py
Labels: feature

#10 editreg.py Added
  core/win/editreg.py
Labels: feature

#11 Project Refactor I
  core/argparser.py
  core/helpers.py
  core/linux/exec.py
  core/utils/argparser.py
  core/utils/helpers.py
  core/utils/logcl.py
  core/win/editreg.py
  core/win/exec.py
  grapheneX.py
Labels: refactor

#13 Files adapted to PEP8
  core/linux/exec.py
  core/utils/argparser.py
  core/utils/helpers.py
  core/utils/logcl.py
  core/win/editreg.py
  core/win/exec.py
  grapheneX.py
Labels: enchancement

#12 Interactive Shell Skeleton
  core/shell.py
  grapheneX.py
Labels: feature

#14 Created basic inital properties in shell and added switch command
  core/cli/shell.py
  core/shell.py
  grapheneX.py
Labels: feature

#15 added commands.py and moved shell commands to commands.py
  core/cli/commands.py
  core/cli/shell.py
  core/utils/helpers.py
  grapheneX.py
Labels: enchancement, feature

#17 pr16 improved
  core/cli/commands.py
  core/cli/help.py
  core/cli/shell.py
  requirements.txt
Labels: enchancement, feature

#18 Added Clear feature
  core/cli/commands.py
  core/cli/shell.py
  grapheneX.py
Labels: feature

#19 Example Hardening Methods for Linux & Windows
  core/hrd/linux/kernel.py
  core/hrd/win/firewall.py
Labels: feature

#20 Refactor & Improve CLI I
  core/cli/commands.py
  core/cli/help.py
  core/cli/shell.py
Labels: enchancement, refactor

#22 Search Command
  core/cli/commands.py
  core/cli/help.py
Labels: feature

#23 switch & use & list commands [CLI]
  core/cli/commands.py
  core/cli/help.py
  core/cli/shell.py
  core/utils/helpers.py
  grapheneX.py
Labels: enchancement, feature

#26 Harden Command Added
  core/cli/commands.py
  core/hrd/linux/kernel.py
  core/hrd/win/firewall.py
  core/linux/exec.py
Labels: feature

#27 Info method added.
  core/cli/commands.py
Labels: feature

#25 Interactive Shell Autocomplete Feature
  core/cli/commands.py
Labels: feature

#28 Fixed uppercase case in namespace selection
  core/cli/commands.py
Labels: fix

#30 Root Check Added
  core/utils/helpers.py
  grapheneX.py
Labels: feature

#31 Win Administrative Access Added
  core/utils/helpers.py
  grapheneX.py
Labels: feature

#29 Added superclass for hardening classes
  core/cli/commands.py
  core/hrd/__init__.py
  core/hrd/linux/kernel.py
  core/hrd/win/firewall.py
  core/utils/helpers.py
Labels: enchancement, refactor
